image: python:3.7

cache:
  paths:
  - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"


stages:
- test
- deploy

test:
  stage: test
  script:
  - apt-get update
  - apt-get install -y binutils libproj-dev python3-pip
  - pip3 install virtualenv
  - rm -rf venv/miare-env
  - virtualenv -p python3 venv/miare-env
  - . venv/miare-env/bin/activate
  - pip3 install -r requirements.txt
  - flake8
  - python3 manage.py test -v 3


deploy:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags
