# Generated by Django 2.1.4 on 2018-12-16 05:54

from django.db import migrations, models
import django.db.models.deletion
import parrot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', parrot.models.UUIDPrimaryKey(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(max_length=200)),
                ('data', models.TextField(blank=True, null=True)),
                ('method', models.CharField(choices=[['POST', 'POST'], ['DELETE', 'DELETE'], ['PATCH', 'PATCH'], ['PUT', 'PUT']], max_length=10)),
                ('sent', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='replayedrequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replayed', to='parrot.RequestLog'),
        ),
        migrations.AddField(
            model_name='capturedrequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captured', to='parrot.RequestLog'),
        ),
    ]
